### ISSUE TITLE
Can't install h5py on windows 10

### ISSUE THREAD

**Issue by hjwk** [udacity/dog-project#13]
Running 
`pip install -r requirements.txt`
fails, saying
`failed building wheel for h5py`

Full error below:

Failed building wheel for h5py
  Running setup.py clean for h5py
  Running setup.py bdist_wheel for scipy ... error
  Complete output from command C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Hubert\\AppData\\Local\\Temp\\pip-build-ainaa87w\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Hubert\AppData\Local\Temp\tmpqpolhcsrpip-wheel- --python-tag cp36:
  lapack_opt_info:
  lapack_mkl_info:
    libraries mkl_rt not found in ['C:\\Users\\Hubert\\AppData\\Local\\conda\\conda\\envs\\dog-project\\lib', 'C:\\', 'C:\\Users\\Hubert\\AppData\\Local\\conda\\conda\\envs\\dog-project\\libs']
    NOT AVAILABLE

  openblas_lapack_info:
    libraries openblas not found in ['C:\\Users\\Hubert\\AppData\\Local\\conda\\conda\\envs\\dog-project\\lib', 'C:\\', 'C:\\Users\\Hubert\\AppData\\Local\\conda\\conda\\envs\\dog-project\\libs']
    NOT AVAILABLE

  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
  C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\numpy\distutils\system_info.py:1051: UserWarning: Specified path C:\projects\numpy-wheels\windows-wheel-builder\atlas-builds\atlas-3.11.38-sse2-64\lib is invalid.
    pre_dirs = system_info.get_paths(self, section, key)
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE

  atlas_3_10_info:
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE

  atlas_threads_info:
  Setting PTATLAS=ATLAS
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE

  atlas_info:
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE

  C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
      Atlas (http://math-atlas.sourceforge.net/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [atlas]) or by setting
      the ATLAS environment variable.
    self.calc_info()
  lapack_info:
    libraries lapack not found in ['C:\\Users\\Hubert\\AppData\\Local\\conda\\conda\\envs\\dog-project\\lib', 'C:\\', 'C:\\Users\\Hubert\\AppData\\Local\\conda\\conda\\envs\\dog-project\\libs']
    NOT AVAILABLE

  C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    self.calc_info()
  lapack_src_info:
    NOT AVAILABLE

  C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    self.calc_info()
    NOT AVAILABLE

  Running from scipy source directory.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Hubert\AppData\Local\Temp\pip-build-ainaa87w\scipy\setup.py", line 415, in <module>
      setup_package()
    File "C:\Users\Hubert\AppData\Local\Temp\pip-build-ainaa87w\scipy\setup.py", line 411, in setup_package
      setup(**metadata)
    File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\numpy\distutils\core.py", line 135, in setup
      config = configuration()
    File "C:\Users\Hubert\AppData\Local\Temp\pip-build-ainaa87w\scipy\setup.py", line 335, in configuration
      config.add_subpackage('scipy')
    File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\numpy\distutils\misc_util.py", line 1001, in add_subpackage
      caller_level = 2)
    File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\numpy\distutils\misc_util.py", line 970, in get_subpackage
      caller_level = caller_level + 1)
    File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\numpy\distutils\misc_util.py", line 907, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\setup.py", line 15, in configuration
      config.add_subpackage('linalg')
    File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\numpy\distutils\misc_util.py", line 1001, in add_subpackage
      caller_level = 2)
    File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\numpy\distutils\misc_util.py", line 970, in get_subpackage
      caller_level = caller_level + 1)
    File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\numpy\distutils\misc_util.py", line 907, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\linalg\setup.py", line 20, in configuration
      raise NotFoundError('no lapack/blas resources found')
  numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

  ----------------------------------------
  Failed building wheel for scipy
  Running setup.py clean for scipy
  Complete output from command C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Hubert\\AppData\\Local\\Temp\\pip-build-ainaa87w\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:

  `setup.py clean` is not supported, use one of the following instead:

    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)

  Add `--force` to your command to use it anyway if you must (unsupported).

  ----------------------------------------
  Failed cleaning build dir for scipy
  Running setup.py bdist_wheel for scikit-learn ... error
  Complete output from command C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Hubert\\AppData\\Local\\Temp\\pip-build-ainaa87w\\scikit-learn\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Hubert\AppData\Local\Temp\tmpo8mobho5pip-wheel- --python-tag cp36:
  Partial import of sklearn during the build process.
  Traceback (most recent call last):
    File "C:\Users\Hubert\AppData\Local\Temp\pip-build-ainaa87w\scikit-learn\setup.py", line 149, in get_scipy_status
      import scipy
  ModuleNotFoundError: No module named 'scipy'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Hubert\AppData\Local\Temp\pip-build-ainaa87w\scikit-learn\setup.py", line 270, in <module>
      setup_package()
    File "C:\Users\Hubert\AppData\Local\Temp\pip-build-ainaa87w\scikit-learn\setup.py", line 260, in setup_package
      .format(scipy_req_str, instructions))
  ImportError: Scientific Python (SciPy) is not installed.
  scikit-learn requires SciPy >= 0.9.
  Installation instructions are available on the scikit-learn website: http://scikit-learn.org/stable/install.html

  ----------------------------------------
  Failed building wheel for scikit-learn
  Running setup.py clean for scikit-learn
Failed to build h5py scipy scikit-learn
Installing collected packages: h5py, cycler, pyparsing, python-dateutil, pytz, matplotlib, scipy, tqdm, theano, pyyaml, keras, scikit-learn, olefile, pillow, decorator, ipython-genutils, traitlets, jupyter-core, pyzmq, jupyter-client, pickleshare, wcwidth, prompt-toolkit, parso, jedi, simplegeneric, colorama, pygments, ipython, tornado, ipykernel
  Running setup.py install for h5py ... error
Exception:
Traceback (most recent call last):
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 50: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 50: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\commands\install.py", line 385, in run
    requirement_set.cleanup_files()
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\req\req_set.py", line 729, in cleanup_files
    req.remove_temporary_source()
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\req\req_install.py", line 977, in remove_temporary_source
    rmtree(self.source_dir)
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\_vendor\six.py", line 686, in reraise
    raise value
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\utils\__init__.py", line 114, in rmtree_errorhandler
    func(path)
PermissionError: [WinError 5] Accès refusé: 'C:\\Users\\Hubert\\AppData\\Local\\Temp\\pip-build-ainaa87w\\h5py\\.eggs\\cython-0.27.3-py3.6-win-amd64.egg\\Cython\\Compiler\\Code.cp36-win_amd64.pyd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\commands\install.py", line 385, in run
    requirement_set.cleanup_files()
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\utils\build.py", line 38, in __exit__
    self.cleanup()
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\utils\build.py", line 42, in cleanup
    rmtree(self.name)
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\_vendor\six.py", line 686, in reraise
    raise value
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 1 more times]
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\Hubert\AppData\Local\conda\conda\envs\dog-project\lib\site-packages\pip\utils\__init__.py", line 114, in rmtree_errorhandler
    func(path)
PermissionError: [WinError 5] Accès refusé: 'C:\\Users\\Hubert\\AppData\\Local\\Temp\\pip-build-ainaa87w\\h5py\\.eggs\\cython-0.27.3-py3.6-win-amd64.egg\\Cython\\Compiler\\Code.cp36-win_amd64.pyd'

**Comment by alexisbcook** [comment]
Thanks for letting me know!  I've amended the README instructions.  (Revised) Step 6 uses a yml file instead and should work for you - please let me know if it does not.
